### PR TITLE
add new logo

### PR DESCRIPTION
**Pull request by amgfernandes**

### CODE REVIEW

**Review by pranjaldhole — COMMENTED** [review]
Do you also want to make changes to the docs so that the logo is visible on the website?

**Comment by cmohl2013** [comment]
Would be good to include the logo into the website. Currently, the website is rendered with Github Pages using the "Cayman" theme. https://github.com/pages-themes/cayman

Maybe we change the theme to be able to include the logo to the title. For example minimal theme supports logo image https://github.com/pages-themes/minimal

what do you think @pranjaldhole @amgfernandes ?

Depending on how the logo is placed, it should have transparent background.

**Comment by pranjaldhole** [comment]
Yes, I agree with @cmohl2013 on changing the website theme to `minimal` and incorporating the logo into the website.
It is probably better to do so before we publish it on bioimage analysis forum and other places.

What do you think @amgfernandes ?

**Comment by amgfernandes** [comment]
I also agree with you both. Having the logo on the website it's a great idea. But of course I wanted to be sure it's fine for @cmohl2013 . Regarding adding it to https://forum.image.sc/ I wanted to wait until I briefly talk to @cmohl2013 .

**Comment by cmohl2013** [comment]
Hi @amgfernandes  form my side, you can go ahead with adding yapic to https://forum.image.sc/  
Thank you for your effort!
I do not know if there is needed any other approval.

When adding the logo to the website we also may acknowledge Joachim from Public Relations Office (do not know if I remember his name correctly) for creating the logo.

**Pull request merged**
